[book]
authors = ["Shawn Tabrizi"]
language = "en"
src = "src"
title = "Rust State Machine"

[output.html]
additional-css = ["src/_gitorial/monaco-setup.css"]
additional-js = ["src/_gitorial/monaco-setup.js"]
git-repository-url = "https://github.com/shawntabrizi/rust-state-machine"
git-repository-icon = "fa-github"
